[project]
name = "torch-fastapi-sample"
version = "0.1.0"
description = "sample"
readme = "README.md"
requires-python = "==3.11.11"
dependencies = [
    "fastapi ==0.115.8",
    "uvicorn ==0.34.0",
    "torch ==2.5.1",
    "transformers ==4.48.3",
]
